### ISSUE TITLE
Feature: Close menu after destroying by menu

### ISSUE THREAD

**Issue by flberger-work** [LucxMangaJet/minetest_presentations#1]
When the menu option "Destroy" is clicked, the presentation is destroyed and dropped in the background, but that might not be visible in smaller windows, as the menu may obscure a large part of the screen.

Feature request: close the menu after "Destroy".

**Comment by LucxMangaJet** [comment]
Implemented in: fd38065ddd8086c3931eefac1c06c257b99d6e2a
