### ISSUE TITLE
Feature: Create presentation block

### ISSUE THREAD

**Issue by flberger-work** [LucxMangaJet/minetest_presentations#2]
The current presentation spawn behaviour is not in line with the general Minetest UX: although it is expected to spawn a decoration-like element in the world, it is spawned by left- (like a weapon) instead of right-clicking (like placing something), and it does not spawn at the clicked location, but at the player location.

Feature request: make the display a block that can be placed with the usual block placement targeting.

Upon placing, the block could immediately be removed, and replaced by the actual presentation object, which would now be located where the player clicked.

**Comment by LucxMangaJet** [comment]
Implemented in: 75fbcd7ef7083862baa037ec60d26a20173b7fc3
I was able to do it without needing a dedicated block. The entity should now feel and behave like a normal node.
