### ISSUE TITLE
Feature: Highlight current settings in menu

### ISSUE THREAD

**Issue by flberger-work** [LucxMangaJet/minetest_presentations#3]
The current setup is not visible in the menu (4:3/16:9, size, ...). If I want to mimic another display I did not build, it takes a lot of figuring out what its the settings are. It would be much easier if they were displayed or highlighted.

**Comment by LucxMangaJet** [comment]
Sadly highlighting buttons is very problematic with the current minetest "formspec" UI system. 
Regardless after the display UI rework this should no longer be a problem as the selected resolution is displayed additionally. 3f904600093d5f0eb63df7776557436a8c27270e
