### ISSUE TITLE
Feature: Basic sanity checks

### ISSUE THREAD

**Issue by flberger-work** [LucxMangaJet/minetest_presentations#5]
The mod should prevent overly stupid things, such as:

- attempting to download something that does not end in png|PNG or jpg|JPG|jpeg
- attempting to download unreasonably large files

For the second, it could do a HTTP `HEAD` request before `GET` and check the `content-length:` header.

This would also conveniently yield the `content-type:` header, which could be checked for a supported MIME type such as `image/png`, providing another safety measure apart from the filename extension.

**Comment by LucxMangaJet** [comment]
Checks for file extension where already in place. 
Added HEAD request and checks for content-length in f890fa98487c7ede5bdd14ec023847667ce9121e. 
I defaulted the maximum filesize to 2MB, i'll have to add a config file for it at one point...
